# Generated by Django 4.2.2 on 2023-06-11 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_code', models.CharField(max_length=10)),
                ('registration_number', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('commercial_description', models.CharField(max_length=200)),
                ('vehicle_identification_number', models.CharField(max_length=50)),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unloaded_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('engine_volume', models.DecimalField(decimal_places=2, max_digits=8)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_code', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=200)),
                ('director_name', models.CharField(blank=True, max_length=100, null=True)),
                ('director_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('director_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('manager_telegram', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('manager_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Logistician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_code', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('order_count', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('phone_numbers', models.ManyToManyField(to='cargo.phonenumber')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_code', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('driver_license', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.car')),
                ('phone_numbers', models.ManyToManyField(to='cargo.phonenumber')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_code', models.CharField(max_length=10)),
                ('cargo_name', models.CharField(max_length=100)),
                ('sender_address', models.CharField(max_length=200)),
                ('delivery_address', models.CharField(max_length=200)),
                ('cargo_tonnage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cargo_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('loading_start', models.BooleanField(blank=True, default=False, null=True)),
                ('cargo_loaded', models.BooleanField(blank=True, default=False, null=True)),
                ('loaded_car_departed', models.BooleanField(blank=True, default=False, null=True)),
                ('car_in_transit', models.BooleanField(blank=True, default=False, null=True)),
                ('unloading_arrived', models.BooleanField(blank=True, default=False, null=True)),
                ('cargo_unloaded', models.BooleanField(blank=True, default=False, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.driver')),
                ('logistician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.logistician')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.fuel'),
        ),
    ]
